Srijan Adhikari - Workshop 0

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
types = ["m2f", "f2m", "kg2lbs", "lbs2kg", "l2ga", "ga2l"]
print("The available conversions are: ")
for values in types:
  print(values)
conversion_type = input("What conversion do you want ? ")
conversion_type = conversion_type.lower()
value1 =  input("Enter the value: ")

def conversion(value1, conversion_type):
  '''This takes 1 value and the conversion type and returns the converted value'''
  try:
    value1 = float(value1)
  except ValueError:
    print("Invalid input")
  else:
    if conversion_type == "m2f":
      return value1 * 3.2808
    elif conversion_type == "f2m":
      return value1/3.2808
    elif conversion_type == "kg2lbs":
      return value1 * 2.2046
    elif conversion_type == "lbs2kg":
      return value1/2.2046
    elif conversion_type == "l2ga":
      return value1 * 0.26417
    elif conversion_type == "ga2l":
      return value1/0.26417

print(f"The converted value is {conversion(value1, conversion_type)}")



The available conversions are: 
m2f
f2m
kg2lbs
lbs2kg
l2ga
ga2l
What conversion do you want ? m2f
Enter the value: 10
The converted value is 32.808


Create a Python program that performs various mathematical operations on a list of numbers.

The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [ ]:
availabe_operations = ["sum", "average", "maximum", "minimum"]

print("The available operations are: ")
for values in availabe_operations:
  print(values)
operation = input("Enter the operation you want to perform : ")
operation = operation.lower()

if operation not in availabe_operations:
  raise ValueError("Invalid operation")

print("Enter the numbers separated by spaces: ")
numbers = input()
numbers = numbers.split()

def sum(values):
  """It takes values and return their sum"""
  sum = 0
  for i in range(len(numbers)):
    sum = sum + int(numbers[i])
  return sum

def calculator(numbers, operation):
  """It takes the numbers and perform the operations on it"""
  for number in numbers:
    if operation == "sum":
      return sum(numbers)
    elif operation == "average":
      return sum(numbers)/len(numbers)
    elif operation == "maximum":
      return max(numbers)
    elif operation == "minimum":
      return min(numbers)

print(f"The {operation} for given numbers is", calculator(numbers, operation))


The available operations are: 
sum
average
maximum
minimum
Enter the operation you want to perform : sum
Enter the numbers separated by spaces: 
1 2 3 4 
The sum for given numbers is 10


Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
initial_list = []
print("Enter 'hehe' to exit the loop.")
while True:
  initial_list_element = input("Enter the element of the list: ")
  if initial_list_element == "hehe":
    break
  initial_list.append(initial_list_element)

print("The initial list is : ",initial_list)

def extract_every_other(lst):
  """ This extracts every other list and returns new list"""
  for value in lst:
    return lst[::2] #lst[start:end:step] from start to end with 2 as a step

print("The new list is : ",extract_every_other(initial_list))


Enter 'hehe' to exit the loop.
Enter the element of the list: 1
Enter the element of the list: 3
Enter the element of the list: 4
Enter the element of the list: 5
Enter the element of the list: 2
Enter the element of the list: hehe
The initial list is :  ['1', '3', '4', '5', '2']
The new list is :  ['1', '4', '2']


Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
initial_list = []
print("Enter 'hehe' to exit the loop.")
while True:
  initial_list_element = input("Enter the element of the list: ")
  if initial_list_element == "hehe":
    break
  initial_list.append(initial_list_element)

print("The initial list is : ",initial_list)

start = int(input("Where do you want final list to start? : "))
end = int(input("Where do you want final list to end? : "))

def get_sublist(lst, start, end):
  """This returns a sublist from a given list, starting from a specified index and ending at another specified index"""
  new_list = lst[start:end+1]
  return new_list

print("The final list will be : ", get_sublist(initial_list,start, end))

Enter 'hehe' to exit the loop.
Enter the element of the list: 1
Enter the element of the list: 
Enter the element of the list: 2
Enter the element of the list: 3
Enter the element of the list: 4
Enter the element of the list: 5
Enter the element of the list: hehe
The initial list is :  ['1', '', '2', '3', '4', '5']
Where do you want final list to start? : 2
Where do you want final list to end? : 5
The final list will be :  ['2', '3', '4', '5']


Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
initial_list = input("Enter values for list with space separation: ").split()

def reverse_list(lst):
  """This reverses the given list and provides the reversed list"""
  return lst[::-1]

print("This is the reversed list: ", reverse_list(initial_list))


Enter values for list with space separation: 1 2 3 4
This is the reversed list:  ['4', '3', '2', '1']


Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.


• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
initial_list = input("Enter values for list with space separation: ").split()

def remove_first_last(lst):
  """Return a sublist without the first and last elements"""
  return lst[1:-1]

print("The final list is ", remove_first_last(initial_list))



Enter values for list with space separation: 1 2 3 4 5
The final list is  ['2', '3', '4']


Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
initial_list = input("Enter values for list with space separation: ").split()

def get_first_n(lst, n):
  """Return the first n elements of the list"""
  return lst[:n]

print("Total number of element in list", len(initial_list))

num = int(input("Enter how many elements do you want ? "))

print("The first", num, "elements are", get_first_n(initial_list, num))

Enter values for list with space separation: 1 2 3 4 5 6
Total number of element in list 6
Enter how many elements do you want ? 3
The first 3 elements are ['1', '2', '3']


Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
initial_list = input("Enter values for list with space separation: ").split()


def get_last_n(lst, n):
  """Return the last n elements of the list"""
  return lst[-n:]

print("The initial list: ", initial_list)
print("Total number of element in list", len(initial_list))

num = int(input("Enter how many elements do you want from end? "))

print("The last", num, "elements are", get_last_n(initial_list, num))


Enter values for list with space separation: 1 2 3 4 5 6
The initial list:  ['1', '2', '3', '4', '5', '6']
Total number of element in list 6
Enter how many elements do you want from end? 2
The last 2 elements are ['5', '6']


Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
initial_list = input("Enter value for initial_list: ").split()

print("The initial list is : ",initial_list)

def reverse_skip(lst):
  """ This extracts every other list and returns new list"""
  return lst[::-2]

print("The new list is : ",reverse_skip(initial_list))

Enter value for initial_list: 1 2 3 4 5
The initial list is :  ['1', '2', '3', '4', '5']
The new list is :  ['5', '3', '1']


Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [1]:
nested_list = [[1, 2], [3, 4], [5]]

new_matrix  = []

for lists in nested_list:
  for values in lists:
    new_matrix.append(values)

print("The flattened list is : ", new_matrix)


The flattened list is :  [1, 2, 3, 4, 5]


Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [17]:
nested_list = [[1, 2], [3, 4], [5, 6]]

new_list = []

def sum(nested_list):
  """This calculates the sum of all elements in a nested list"""
  sum = 0
  for lists in nested_list:
      for value in lists:
        new_list.append(value)
        sum = sum + value
  return sum

def average_nested(lst):
  """This provides with the average"""
  return sum(lst)/len(new_list)

print("The average of all elements is : ", average_nested(nested_list))

The average of all elements is :  3.5


**NUMPYY**

In [20]:
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


**To - Do - NumPy**

Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np


empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)

Empty Array:
 [[6.61955361e-310 2.06527582e-316]
 [1.58101007e-322 1.58101007e-322]]


In [ ]:
ones_array = np.ones((4, 2))
print("\nAll Ones Array:\n", ones_array)



All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
fill_value_array = np.full((3, 3), 7)
print("\nArray filled with value 7:\n", fill_value_array)


Array filled with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Given Array:\n", zeros_like_array)


Zeros Like Given Array:
 [[0 0 0]
 [0 0 0]]


In [ ]:
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Given Array:\n", ones_like_array)



Ones Like Given Array:
 [[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted Numpy Array:\n", numpy_array)


Converted Numpy Array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)



3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nMean of random array:\n", mean_value)


Mean of random array:
 0.45360561277518374


In [ ]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nMinimum value:", min_value, " Maximum value:", max_value)


Minimum value: 0.0189898837930067  Maximum value: 0.9987921252432198


In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element as 1:\n", zero_array)


Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)


Reversed array:
 [0 4 0 0 2 1]


In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border of 1s and 0s inside:\n", border_array)


2D Array with border of 1s and 0s inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)



8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
sum_array = x + y
print("\nSum of x and y:\n", sum_array)


Sum of x and y:
 [[ 6  8]
 [10 13]]


In [ ]:
diff_array = x - y
print("\nDifference of x and y:\n", diff_array)


Difference of x and y:
 [[-4 -4]
 [-4 -3]]


In [ ]:
multiplied_array = x * 2
print("\nMultiplication of x with 2:\n", multiplied_array)


Multiplication of x with 2:
 [[ 2  4]
 [ 6 10]]


In [ ]:
squared_array = x ** 2
print("\nSquare of each element in x:\n", squared_array)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [ ]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("\nDot product of v and w:\n", dot_v_w)
print("\nDot product of x and v:\n", dot_x_v)
print("\nDot product of x and y:\n", dot_x_y)


Dot product of v and w:
 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
concatenated_xy = np.concatenate((x, y), axis=0)
concatenated_vw = np.vstack((v, w))
print("\nConcatenated x and y along rows:\n", concatenated_xy)
print("\nConcatenated v and w along columns:\n", concatenated_vw)



Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenated v and w along columns:
 [[ 9 10]
 [11 12]]


In [ ]:
try:
    concatenated_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenated x and v:\n", concatenated_xv)
except ValueError as e:
    print("\nError when concatenating x and v:\n", e)
    print("Explanation: The error occurs because x is a 2x2 matrix, and v is a 1D array of size 2. To concatenate correctly, v needs to be reshaped into a 2D array.")


Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: The error occurs because x is a 2x2 matrix, and v is a 1D array of size 2. To concatenate correctly, v needs to be reshaped into a 2D array.


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [ ]:
#1
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("\nA * A^(-1) (Identity Matrix):\n", identity_matrix)



A * A^(-1) (Identity Matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
#2
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nIs AB equal to BA?", np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA? False


In [ ]:
#3
AB_T = np.transpose(AB)
B_TA_T = np.dot(np.transpose(B), np.transpose(A))
print("\n(AB)^T:\n", AB_T)
print("\nB^T A^T:\n", B_TA_T)
print("\nIs (AB)^T equal to B^T A^T?", np.array_equal(AB_T, B_TA_T))


(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T? True


In [ ]:
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])
A_inv_matrix = np.linalg.inv(A_matrix)
X = np.dot(A_inv_matrix, B_matrix)
print("\nSolution of the linear equations:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])


Solution of the linear equations:
x = 2.0
y = 1.0
z = -2.0


10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
n = 1000000
list1 = list(range(n))
list2 = list(range(n))
array1 = np.arange(n)
array2 = np.arange(n)

# Python Lists
start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(n)]
print("\nTime for Python list addition:", time.time() - start_time, "seconds")

# NumPy Arrays
start_time = time.time()
numpy_sum = array1 + array2
print("Time for NumPy array addition:", time.time() - start_time, "seconds")


Time for Python list addition: 0.1333765983581543 seconds
Time for NumPy array addition: 0.006696939468383789 seconds


In [ ]:
# 2
# Python Lists
start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(n)]
print("\nTime for Python list multiplication:", time.time() - start_time, "seconds")

# NumPy Arrays
start_time = time.time()
numpy_product = array1 * array2
print("Time for NumPy array multiplication:", time.time() - start_time, "seconds")


Time for Python list multiplication: 0.16466856002807617 seconds
Time for NumPy array multiplication: 0.011977672576904297 seconds


In [ ]:
# 3
# Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(n))
print("\nTime for Python list dot product:", time.time() - start_time, "seconds")

# NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
print("Time for NumPy array dot product:", time.time() - start_time, "seconds")



Time for Python list dot product: 0.15959930419921875 seconds
Time for NumPy array dot product: 0.0024275779724121094 seconds
